apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/jaehyuk-lee/nginx-ttest:release
          env:
          - name: WAS_IP
            value: nodejs-alb-456367258.ap-northeast-1.elb.amazonaws.com
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: WAS-nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: ghcr.io/jaehyuk-lee/nodejs-test:release
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-nginx-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-nginx
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: WAS-nodejs-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: WAS-nodejs
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
