# nginx Deployment 정의
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: swordbill/nginx:v2
          ports:
            - containerPort: 80
      nodeSelector: # 노드 유형 지정
        node-type: web

---
# tomcat Deployment 정의
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: swordbill/tomcat:9.0.87
          ports:
            - containerPort: 8080
      nodeSelector: # 노드 유형 지정
        node-type: was
