apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
spec:
  replicas: 8
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: swordbill/nginx:1.18
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 25
        - pause: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tomcat
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: swordbill/tomcat:9.0.87
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 25
        - pause: {}
---