apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx_v2
  namespace: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: swordbill/nginx:v2
          ports:
            - containerPort: 80
      nodeSelector:
        node-type: web
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tomcat
  namespace: tomcat
spec:
  replicas: 8
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: swordbill/tomcat:9.0.87
          ports:
            - containerPort: 8080
      nodeSelector:
        node-type: was
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
