apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: swordbill/nginx:1.18
          ports:
            - containerPort: 80
      nodeSelector:
        node-type: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: swordbill/tomcat:9.0.87
          ports:
            - containerPort: 8080
      nodeSelector:
        node-type: was

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-to-tomcat
spec:
  type: LoadBalancer
  selector:
    app: nginx # nginx가 포함된 Pod 선택
  ports:
    - protocol: TCP
      port: 80 # nginx가 사용하는 포트
      targetPort: 80 # nginx Pod의 포트
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    app: tomcat # tomcat이 포함된 Pod 선택
  ports:
    - protocol: TCP
      port: 8080 # tomcat이 사용하는 포트
      targetPort: 8080 # tomcat Pod의 포트
