apiVersion: v1
kind: Service
metadata:
  name: myapp-service-nginx
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-tomcat
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
