apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  http.port: "2020"
  http.server: "On"
  read.head: "Off"
  read.tail: "On"
  cluster.name: "App-EKS"  # 변경할 클러스터 이름
  logs.region: "ap-northeast-1"         # 변경할 로그 지역
